### PR TITLE
Release/2.7.1

### PR DESCRIPTION
**Pull request by jholloc**
Release 2.7.1

This is a patch release of 2.7.0 including fixes to build on Freia (UKAEA) and fixes to Cap'n Serialisation from issues found during development of IMAS remote data access.

We are also now including the C++ guideline support library (GSL) to avoid needing to rely on Boost::span which is only available in newer versions.

### CODE REVIEW

**Review by stephen-dixon — APPROVED** [review]
Builds successfully on both client and server machines at UKAEA. Regression tests passing.

**Review by olivhoenen — APPROVED** [review]
Looking fine

**Comment by DorisBDR** [comment]
question why do we ship the configuration files like imas and mast (under /etc/machine.d)...these are specific files for a particular site?
is it the plan to collect there all the sites configuration?

**Comment by jholloc** [comment]
> question why do we ship the configuration files like imas and mast (under /etc/machine.d)...these are specific files for a particular site? is it the plan to collect there all the sites configuration?

It's mostly for convenience. These are the configuration files for running the server on those machines.

I agree this is probably the wrong place for them and we should look to move them elsewhere, especially now UDA is a public repo.

**Review by SimonPinches — APPROVED** [review]
lgtm

**Comment by jholloc** [comment]
Merging this for 2.7.1 release. We will look at the ITER CODAC changes for 2.7.2 release.

**Pull request merged**
